### ISSUE TITLE
Unknown class in Interface Builder

### ISSUE THREAD

**Issue by burakkilic** [TTTAttributedLabel/TTTAttributedLabel#137]
Hi;

I am using TTTAttributeLabel as custom class in storyboard. I am getting:

```
 Unknown class TTTAttributedLabel in Interface Builder file.
```

Why I am getting this?

**Comment by akshaypakanati** [comment]
@burakkilic  am also facing same problem with this class in swift project with "use_frameworks!"
I've searched all posts and tried everything, not getting solved for me..
can you please help me out??

**Comment by burakkilic** [comment]
Hi;

I don't remember how I solved that, but now my Podfile is:

    platform :ios, '8.0'
use_frameworks!

pod 'TTTAttributedLabel'
pod 'FLAnimatedImage', '~> 1.0'
pod 'Fabric'
pod 'Crashlytics'

and is working. Hope this helps.

**Comment by akshaypakanati** [comment]
i'm also using same kind of podfile..
but my problem is whenever i set TTTAttriburedLabel in IB , i was unable to set module name as "current-MyModuleName".
I've tried with renaming class name etc., and quitting xcode , clearing derived data, deleting cached xibs etc.,
still i'm unable to set custom class in my nib.. :-( 

ANy other suggestions please?

**Comment by burakkilic** [comment]
Are you using XCode 7.2?

**Comment by akshaypakanati** [comment]
Yes

**Comment by illyaBakurov** [comment]
Hi,

I am having the same issue.
My CocoaPods version is 1.0.1

and here is my CocoaPods:
`
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target '@Sight' do
    
pod 'TTTAttributedLabel'

end
`
It sees the TTTAttributedLabel framework and I can set it to the UILabel object in Interface Builder and Module i set up properly. I am using .xib file. When I run the project it installs to my device normally. But when I go to the view controller which uses this label, it crashes.

Here is the copy of an error:
`
 warning: IB Designables: Using class UILabel for object with custom class because the class _TtC6_Sight18TTTAttributedLabel does not exist
`

And also if I comment all IB_DESIGNABLE and IBINSPECTABLE in TTTAttributedLabel.h the error will persist.

I was trying to remove the framework from CocoaPods and simply drag-and-drop it to the project, but the error still was there.

Have no idea how to fix it and need help with it.
