### ISSUE TITLE
Use with NSTextAttachment

### ISSUE THREAD

**Issue by dennisreimann** [TTTAttributedLabel/TTTAttributedLabel#287]
I can’t seem to get NSTextAttachment (iOS 7) in an TTTAttributedLabel to work. It works fine with an UILabel, though. I dug around the sources, but could not find a reason for this - my initial assumption was that it might be related to the custom drawing code, but I commented out the UILabel overwrites, but it didn't work either.

Here's the code I'm using:

``` objective-c
NSTextAttachment *textAttachment = [[NSTextAttachment alloc] init];
UIImage *image = [UIImage imageNamed:@"MyImage"];
NSAssert(image, nil);
textAttachment.image = image;
textAttachment.bounds = CGRectMake(0, 0, image.size.width, image.size.height);
NSAttributedString *attributedString = [NSAttributedString attributedStringWithAttachment:textAttachment];
tttAttributedLabel.text = attributedString;
```

**Comment by jpmcglone** [comment]
@mattt how do we get this working? Your last message seems to imply that we can make it work with Text Kit?? In TTTAttributedLabel?

Trying to get a little icon next to all my (@username)'s in a TTTAttributedLabel and could really use some help.  I got the regex stuff down, and have the ranges.. since I can't use NSTextAttachment, what can I do? *looking more into Text Kit, but if you can help nudge me in the right direction I'd be forever grateful*
