### ISSUE TITLE
Setting UILabel properties (like font) after setting text does nothing

### ISSUE THREAD

**Issue by a2** [TTTAttributedLabel/TTTAttributedLabel#464]
I noticed that if I set `text` and then `font`, the attributed text is not regenerated.

**Comment by tamastimar** [comment]
I've run into the same issue.

I can understand that it's by design but it seems from debugging that in this case `IBInspectable` annotations in the lib are useless since those values (i.e. customized in IB) will be set after the `text` property is configured in `initWithCoder:`.

Did I miss something?
