### ISSUE TITLE
`addLinkWithTextCheckingResult:attributes:` sets `linkAttributes` too

### ISSUE THREAD

**Issue by kylef** [TTTAttributedLabel/TTTAttributedLabel#484]
When adding a link with text checking results, and passing in attributes that are empty, or not equal to `- [TTTAttributedLabel textAttributes]`. `- [TTTAttributedLabel textAttributes]` is later set for this range regardless. 

This is due to the implementation of `tintColorDidChange` in TTTAttributedLabel which iterates over the link attributes and set's the `linkAttributes` attributes.

This is certainly not what is documented for this parameter for this method:

> The attributes to be added to the text in the range of the specified link. **If `nil`, no attributes are added.**

**Comment by getaaron** [comment]
Pull request https://github.com/TTTAttributedLabel/TTTAttributedLabel/pull/419 is intended to address this and some other related issues. It will no longer merge because it's been a while. I might have some time to update it this week, but anyone interested can take a look at it sooner.

It still has an outstanding question for the maintainer of the library (whether to make two separate arrays, or introduce breaking changes for `links`.)
